import { useState } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import { ArrowRight, CalendarDays, Check, ChevronDown, Clock3, Facebook, HeartPulse, Instagram, Linkedin, Mail, Menu, Phone, Play, ShieldCheck, Star, Stethoscope, UserRound, X } from "lucide-react";

const services = [
  { slug: "trained-attendants", name: "Trained Attendants", icon: UserRound, text: "Compassionate day-to-day support for patients and families." },
  { slug: "nursing", name: "Nursing Care", icon: HeartPulse, text: "Certified nurses for skilled care, recovery and chronic needs." },
  { slug: "physiotherapy", name: "Physiotherapy", icon: Stethoscope, text: "Personalised rehabilitation plans delivered at home." },
  { slug: "medical-equipment", name: "Medical Equipment", icon: ShieldCheck, text: "Reliable equipment rentals with doorstep delivery." },
  { slug: "critical-care", name: "Critical Care", icon: HeartPulse, text: "Hospital-grade ICU support for complex care at home." },
  { slug: "mother-baby-care", name: "Mother & Baby Care", icon: UserRound, text: "Gentle, expert support for new mothers and newborns." },
  { slug: "elder-care", name: "Elder Care", icon: HeartPulse, text: "Respectful companionship and health support for seniors." },
  { slug: "doctor-consultation", name: "Doctor Consultation", icon: Stethoscope, text: "Experienced doctors who come to your doorstep." },
];
const cities = ["Bengaluru", "Mumbai", "Delhi NCR", "Hyderabad", "Chennai", "Pune", "Kolkata", "Ahmedabad"];
const articles = [
  ["Elder Care", "Different Types of Elder Care Services", "Practical guidance to help your loved ones live with comfort and confidence."],
  ["Physiotherapy", "How physiotherapy at home supports faster recovery", "Simple ways a consistent plan can bring mobility back into everyday life."],
  ["Critical Care", "When hospital-level care comes home", "What families should know about building a safe, supportive care environment."],
];

function Header() {
  const [open, setOpen] = useState(false);
  const [location] = useLocation();
  return <header className="site-header">
    <div className="topbar"><div className="container topbar-inner"><span>India’s trusted home healthcare provider</span><span className="topbar-right"><Clock3 size={13}/> Available 8am–8pm, Monday to Sunday</span></div></div>
    <nav className="nav container">
      <Link href="/" className="brand"><span className="brand-mark">P</span><span><b>PORTEA</b><small>HEAL AT HOME</small></span></Link>
      <button className="mobile-menu" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X/> : <Menu/>}</button>
      <div className={`nav-links ${open ? "show" : ""}`}>
        <div className="nav-dropdown"><span>Our Services <ChevronDown size={14}/></span><div className="dropdown-menu">{services.slice(0,6).map(s => <Link key={s.slug} href={`/${s.slug}`} onClick={() => setOpen(false)}>{s.name}</Link>)}</div></div>
        <Link className={location === "/about-us" ? "active" : ""} href="/about-us">About Us</Link><Link href="/blogs">Blogs</Link><a href="tel:18001212323" className="phone"><Phone size={15}/> 1800 121 2323</a><Link href="/contact-us" className="btn btn-primary small">Book Now</Link>
      </div>
    </nav>
  </header>
}
function Footer() { return <footer><div className="container footer-grid"><div><Link href="/" className="brand footer-brand"><span className="brand-mark">P</span><span><b>PORTEA</b><small>HEAL AT HOME</small></span></Link><p className="muted">Quality medical care, brought to the comfort of your home.</p><div className="socials"><Facebook size={17}/><Instagram size={17}/><Linkedin size={17}/></div></div><div><h4>Company</h4><Link href="/about-us">About us</Link><Link href="/careers">Careers</Link><Link href="/contact-us">Contact us</Link><Link href="/partner-with-us">Partner with us</Link></div><div><h4>Popular services</h4><Link href="/nursing">Nursing at home</Link><Link href="/physiotherapy">Physiotherapy</Link><Link href="/doctor-consultation">Doctor consultations</Link><Link href="/medical-equipment">Medical equipment</Link></div><div><h4>Get in touch</h4><a href="tel:18001212323"><Phone size={15}/> 1800 121 2323</a><a href="mailto:bookings@portea.com"><Mail size={15}/> bookings@portea.com</a><p className="muted small-text">Mon–Sun · 8am–8pm</p></div></div><div className="container footer-bottom"><span>© 2026 Portea Medical. All rights reserved.</span><span>Privacy policy &nbsp; Terms of use</span></div></footer> }
function BookingCard() { return <div className="booking-card"><div><label>What care do you need?</label><select><option>Select a service</option>{services.map(s => <option key={s.slug}>{s.name}</option>)}</select></div><Link href="/contact-us" className="btn btn-primary">Book Now <ArrowRight size={16}/></Link></div> }
function Hero() { return <section className="hero"><div className="container hero-inner"><div className="hero-copy"><div className="eyebrow">INDIA’S HOME HEALTHCARE PIONEERS · SINCE 2013</div><h1>Quality medical care in the <em>comfort of your home</em></h1><p>Doctors, nurses, physiotherapists and trained attendants — compassionate, expert care delivered to your doorstep.</p><BookingCard/><div className="trust-row"><div><b>20 Lakh+</b><span>patients served</span></div><div><b>135</b><span>cities across India</span></div><div><b>100+</b><span>hospital partners</span></div></div></div><div className="hero-image"><div className="image-wash"></div><img src="https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=900&q=85"/><div className="hero-badge badge-one"><b>20 Lakh+</b><span>patients served</span></div><div className="hero-badge badge-two"><b>100+</b><span>hospital partners</span></div></div></div></section> }
function Services() { return <section className="section services-section"><div className="container"><div className="section-heading"><div className="eyebrow">WHAT WE DO</div><h2>Medical services offered at home</h2><p>Portea Medical offers a variety of healthcare services in the comfort of our patient’s homes.</p></div><div className="service-grid">{services.map(s => <Link href={`/${s.slug}`} className="service-card" key={s.slug}><div className="service-icon"><s.icon size={22}/></div><div><h3>{s.name}</h3><p>{s.text}</p></div><ArrowRight size={19} className="card-arrow"/></Link>)}</div><div className="center"><Link href="/services" className="text-link">View all services <ArrowRight size={16}/></Link></div></div></section> }
function Proof() { return <section className="proof section"><div className="container proof-grid"><div className="proof-photo"><img src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=900&q=85"/><div className="photo-note"><Star fill="currentColor" size={15}/> Rated 4.8 by families</div></div><div className="proof-copy"><div className="eyebrow">WHY PORTEA</div><h2>Care that feels personal, because it is.</h2><p>From the first conversation to every follow-up, our care teams work around your family’s needs. We bring clinical excellence, warmth and accountability to every home visit.</p><div className="check-list"><div><Check/> Background-verified professionals</div><div><Check/> Personalised care plans</div><div><Check/> Dedicated care coordinators</div></div><Link href="/about-us" className="btn btn-outline">Know more <ArrowRight size={16}/></Link></div></div></section> }
function Testimonial() { return <section className="quote-section"><div className="container quote-inner"><div className="eyebrow">FAMILIES SPEAK</div><div className="quote-mark">“</div><blockquote>The inputs shared were very useful in helping me manage by diabetes better. The explanation was excellent and the care team was patient, reassuring and thorough.</blockquote><div className="quote-author"><div className="avatar">RS</div><div><b>Ramesh S.</b><span>Family member · Bengaluru</span></div></div></div></section> }
function Articles() { return <section className="section articles"><div className="container"><div className="section-heading split"><div><div className="eyebrow">FROM THE JOURNAL</div><h2>Small steps. Better health.</h2></div><Link href="/blogs" className="text-link">Read all stories <ArrowRight size={16}/></Link></div><div className="article-grid">{articles.map((a,i)=><Link href={`/blog/${i+1}`} className="article-card" key={a[1]}><div className={`article-img image-${i}`}></div><div className="article-body"><span>{a[0]}</span><h3>{a[1]}</h3><p>{a[2]}</p><b>Read more <ArrowRight size={15}/></b></div></Link>)}</div></div></section> }
function Home() { return <><Header/><main><Hero/><Services/><Proof/><Testimonial/><Articles/><section className="cta-band"><div className="container cta-inner"><div><div className="eyebrow">NEED CARE AT HOME?</div><h2>Let’s make care feel closer.</h2><p>Speak to our care team and find the right support for your family.</p></div><Link href="/contact-us" className="btn btn-light">Book an appointment <ArrowRight size={17}/></Link></div></section></main><Footer/></> }
function InnerPage({type, slug}:{type:string;slug?:string}) { const service = services.find(s=>s.slug===slug); const title = service?.name || ({"about-us":"About Portea","contact-us":"We’re here to help","careers":"Build a career that cares","blogs":"The Portea journal","services":"Care designed around you"}[type] || "Portea Medical"); const description = service?.text || (type === "about-us" ? "India’s home healthcare pioneers. Quality medical care, brought to the comfort of your home." : type === "careers" ? "Join a team that is changing the way India experiences healthcare." : type === "blogs" ? "Thoughtful advice, expert perspectives and stories from the world of home healthcare." : "Tell us what you need and our care team will get back to you shortly."); return <><Header/><main><section className="inner-hero"><div className="container inner-hero-inner"><div className="eyebrow">PORTEA MEDICAL</div><h1>{title}</h1><p>{description}</p>{type === "contact-us" ? <BookingCard/> : <Link href={type === "blogs" ? "/contact-us" : "/contact-us"} className="btn btn-primary">Talk to our care team <ArrowRight size={16}/></Link>}</div></section>{type === "blogs" ? <BlogListing/> : type === "contact-us" ? <ContactContent/> : <GeneralContent service={service} type={type}/>}</main><Footer/></> }
function GeneralContent({service,type}:{service?:typeof services[number],type:string}) { return <section className="section"><div className="container content-grid"><div><div className="eyebrow">CARE, ON YOUR TERMS</div><h2>{service ? `Trusted ${service.name.toLowerCase()} at home` : "Healthcare that starts with listening"}</h2><p>We believe the best care is care that fits into real life. Our experienced professionals work with you, your doctor and your family to create a plan that feels clear, practical and reassuring.</p><p>With trained teams, thoughtful coordination and reliable follow-through, Portea brings the confidence of clinical care to your living room.</p><div className="check-list"><div><Check/> Verified professionals</div><div><Check/> Flexible visit plans</div><div><Check/> Support when you need it</div></div></div><div className="content-panel"><h3>How it works</h3><div className="step"><b>01</b><span><strong>Tell us what you need</strong><small>Call or book an appointment online.</small></span></div><div className="step"><b>02</b><span><strong>Meet your care team</strong><small>We match you with the right professional.</small></span></div><div className="step"><b>03</b><span><strong>Feel supported at home</strong><small>Care plans that evolve with you.</small></span></div></div></div></section> }
function BlogListing() { return <section className="section"><div className="container"><div className="blog-list">{[...articles,...articles].map((a,i)=><Link href={`/blog/${i+1}`} className="blog-row" key={i}><div className={`article-img image-${i%3}`}></div><div><span>{a[0]} · September 2026</span><h3>{a[1]}</h3><p>{a[2]}</p><b>Read story <ArrowRight size={15}/></b></div></Link>)}</div></div></section> }
function ContactContent() { return <section className="section"><div className="container contact-grid"><div><div className="eyebrow">CONTACT PORTEA</div><h2>Let’s talk about the right care for you.</h2><p>Our care coordinators are available to answer questions, understand your needs and help you take the next step.</p><div className="contact-detail"><Phone/><div><b>1800 121 2323</b><span>Call us 8am–8pm</span></div></div><div className="contact-detail"><Mail/><div><b>bookings@portea.com</b><span>We reply within one business day</span></div></div></div><form className="contact-form" onSubmit={e=>e.preventDefault()}><h3>Request a callback</h3><input placeholder="Your name"/><input placeholder="Phone number"/><input placeholder="City"/><textarea placeholder="Tell us how we can help" rows={4}/><button className="btn btn-primary">Submit request <ArrowRight size={16}/></button></form></div></section> }
function SlugPage({slug}:{slug:string}) { const label = slug.split("-").map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(" "); return <InnerPage type={slug} slug={services.some(s=>s.slug===slug)?slug:undefined}/> }
function CityServicePage({service,city}:{service:string;city:string}) { const serviceName = services.find(s=>s.slug===service)?.name || service.split("-").map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(" "); const cityName = city.split("-").map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(" "); return <><Header/><main><section className="inner-hero"><div className="container inner-hero-inner"><div className="eyebrow">PORTEA MEDICAL · {cityName.toUpperCase()}</div><h1>{serviceName} at home in {cityName}</h1><p>Trusted, compassionate healthcare from trained professionals, delivered to your doorstep in {cityName}.</p><Link href="/contact-us" className="btn btn-primary">Book a visit <ArrowRight size={16}/></Link></div></section><GeneralContent service={services.find(s=>s.slug===service)} type={service}/></main><Footer/></> }
function BlogDetail({id}:{id:string}) { const article = articles[(Number(id)-1)%articles.length]; return <><Header/><main><section className="inner-hero"><div className="container inner-hero-inner"><div className="eyebrow">{article[0].toUpperCase()} · PORTEA JOURNAL</div><h1>{article[1]}</h1><p>{article[2]}</p></div></section><section className="section"><div className="container content-grid"><div><p>Good healthcare begins with information you can trust. In this guide, our care teams share practical ideas that help families make confident decisions, one small step at a time.</p><p>Every person and every home is different. That is why the right plan is one that brings together clinical expertise, clear communication and the routines that matter most to you.</p><h2>Care that fits real life</h2><p>Our professionals meet families where they are, listen carefully and follow through. If you have questions about home healthcare, our coordinators are here to help.</p></div><div className="content-panel"><div className="eyebrow">NEED SUPPORT?</div><h3>Talk to our care team</h3><p className="muted">Get clear answers and find the right service for your family.</p><Link href="/contact-us" className="btn btn-primary">Contact us <ArrowRight size={16}/></Link></div></div></section></main><Footer/></> }
function App() { return <Switch><Route path="/" component={Home}/><Route path="/blogs"><InnerPage type="blogs"/></Route><Route path="/blog/:id">{params=><BlogDetail id={params.id}/>}</Route><Route path="/about-us"><InnerPage type="about-us"/></Route><Route path="/contact-us"><InnerPage type="contact-us"/></Route><Route path="/careers"><InnerPage type="careers"/></Route><Route path="/services"><InnerPage type="services"/></Route><Route path="/partner-with-us"><InnerPage type="partner-with-us"/></Route><Route path="/faqs"><InnerPage type="faqs"/></Route><Route path="/testimonials"><InnerPage type="testimonials"/></Route>{services.map(s=><Route key={s.slug} path={`/${s.slug}`}><InnerPage type={s.slug} slug={s.slug}/></Route>)}<Route path="/:service/:city">{params=><CityServicePage service={params.service} city={params.city}/>}</Route><Route path="/:slug">{params=><SlugPage slug={params.slug}/>}</Route><Route><InnerPage type="about-us"/></Route></Switch> }
export default App;
