import {
  Accessibility,
  Armchair,
  Baby,
  Bed,
  Briefcase,
  Building,
  Building2,
  CalendarHeart,
  Factory,
  Footprints,
  GraduationCap,
  HandHeart,
  HandHelping,
  HardHat,
  Heart,
  HeartHandshake,
  Hotel,
  House,
  MessageCircleHeart,
  School,
  Smile,
  Sparkles,
  Sunrise,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { ServiceIcon } from "@shared/services";

export const SERVICE_ICON_COMPONENTS: Record<ServiceIcon, LucideIcon> = {
  "heart-handshake": HeartHandshake,
  "hand-heart": HandHeart,
  "hand-helping": HandHelping,
  heart: Heart,
  armchair: Armchair,
  baby: Baby,
  smile: Smile,
  "message-circle-heart": MessageCircleHeart,
  "calendar-heart": CalendarHeart,
  sunrise: Sunrise,
  footprints: Footprints,
  accessibility: Accessibility,
  bed: Bed,
  house: House,
  users: Users,
  "building-2": Building2,
  building: Building,
  hotel: Hotel,
  school: School,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  factory: Factory,
  "hard-hat": HardHat,
  sparkles: Sparkles,
};
